[package]
name = "reduced-ui-animations-mod-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
whoami = "1.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [] }
pretty_assertions = "1.4"
serde_json = "1.0"
